'use client';

import Footer from 'components/Footer/page';
import Header from 'components/Header/page';
import Lines from 'components/Lines/page';
import ScrollToTop from 'components/ScrollToTop/page';
import { ThemeProvider } from 'next-themes';
import { Inter } from 'next/font/google';
import './globals.css';

import ToasterContext from './context/ToastContext';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`dark:bg-black ${inter.className}`}>
        <ThemeProvider
          enableSystem={false}
          attribute="class"
          defaultTheme="light"
        >
          <Lines />
          <Header />
          <ToasterContext />
          {children}
          <Footer />
          <ScrollToTop />
        </ThemeProvider>
      </body>
    </html>
  );
}

// import CategoryMenu from 'comp/CategoryMenu';
// import Footer from 'comp/Footer';
// import Nav from 'comp/Nav';
// import AuthProvider from 'context/AuthProvider';
// import { Montserrat, Open_Sans } from 'next/font/google';
// import { ReactNode } from 'react';
// import { Toaster } from 'react-hot-toast';
// import Analytics from 'util/Analytics';
// import './globals.css';

// type Props = {
//   children?: ReactNode;
// };

// const montserrat = Montserrat({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-montserrat',
// });

// const openSans = Open_Sans({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-opensans',
// });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default async function RootLayout({ children }: Props) {
//   return (
//     <html
//       lang="en"
//       className="scrollbar-thumb-rounded-full scrollbar-track-rounded-full scrollbar-thin scrollbar-thumb-pry-400 scrollbar-track-slate-200"
//     >
//       <Analytics />
//       <body
//         className={`font-sans ${montserrat.variable} ${openSans.variable} antialiased print:bg-secondary`}
//       >
//         <AuthProvider>
//           <Toaster position="bottom-center" reverseOrder={false} />
//           <Nav />
//           <div className="min-h-screen flex flex-col justify-between bg-slate-50">
//             <div className="fixed md:hidden z-20">
//               <CategoryMenu />
//             </div>
//             <div className="flex relative">
//               <div className="mdDown:hidden sticky h-full top-0 left-0">
//                 <CategoryMenu />
//               </div>
//               <div className="pt-[4.75rem] min-h-screen md:pt-[5.5rem] lg:pt-[6.5rem] pb-[0.75rem] md:pb-[1.5rem] lg:pb-[2.5rem] mx-auto">
//                 {children}
//               </div>
//             </div>
//             <div id="mainModalContainer" />
//             <Footer />
//           </div>
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }
